;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Game.TurnState.ChaosState.IsINChaosState",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.ConsumeRessources.ConsumeByNation_Event",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.ConsumeRessources.FinishConsumeByNation_Event",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.ConsumeRessources.IsCurrentState",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.CreateRessources.CreateByNation_Event",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.CreateRessources.FinishCreateByNation_Event",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.CreateRessources.IsCurrentState",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.DispachRessources.DispatchBySlot_Event",DevComment="(Name, String)")
+GameplayTagList=(Tag="Game.TurnState.DispachRessources.FinishDispatchement_Event",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.DispachRessources.FinishDispatchementByNation_Event",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.DispachRessources.IsCurrentState",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.DispachRessources.StartDispatchement_Event",DevComment="")
+GameplayTagList=(Tag="Game.TurnState.GiveEnergy.IsCurrentState",DevComment="")
+GameplayTagList=(Tag="Nation.State.Energy.UpdateValue_Event",DevComment="")
+GameplayTagList=(Tag="Nation.State.Interact.Interact_Event",DevComment="")
+GameplayTagList=(Tag="Player.State.Interact.CurrentNationPowered_Object",DevComment="")
+GameplayTagList=(Tag="Player.State.UI_Interaction.SelectedContinent_Object",DevComment="")
+GameplayTagList=(Tag="Player.State.UI_Interaction.UpdateSelectedContinent_Event",DevComment="")
+GameplayTagList=(Tag="Slot.Action.ChaosAction.DestroyAllRessources_Event",DevComment="")
+GameplayTagList=(Tag="Slot.Action.ChaosAction.RailsLevelDown_Event",DevComment="")
+GameplayTagList=(Tag="Slot.State.AssignedNation.Change_Event",DevComment="")
+GameplayTagList=(Tag="Slot.State.ChaosLevel.IsInFirstLayer",DevComment="")
+GameplayTagList=(Tag="Slot.State.ChaosLevel.IsInSecondLayer",DevComment="")
+GameplayTagList=(Tag="Slot.State.ChaosLevel.IsInThirdLayer",DevComment="")
+GameplayTagList=(Tag="Slot.State.IsInusable",DevComment="")

